/*
 * This file was generated by the generate_ast.py script.
 */

#pragma once

#include <memory>
#include <optional>

#include "lexer.hpp"


struct Expression
{
    class Visitor;
    class Binary;
    class Grouping;
    class Literal;
    class Unary;
    class Variable;
    class Assignment;
    virtual ~Expression() = default;
    virtual void accept(Visitor& visitor) const = 0;
};


struct Expression::Binary : Expression
{
    Binary(std::unique_ptr<Expression> left, Token op, std::unique_ptr<Expression> right);
    void accept(Expression::Visitor& visitor) const override;
    std::unique_ptr<Expression> left;
    Token op;
    std::unique_ptr<Expression> right;
};


struct Expression::Grouping : Expression
{
    Grouping(std::unique_ptr<Expression> expression);
    void accept(Expression::Visitor& visitor) const override;
    std::unique_ptr<Expression> expression;
};


struct Expression::Literal : Expression
{
    Literal(Token::Literal value);
    void accept(Expression::Visitor& visitor) const override;
    Token::Literal value;
};


struct Expression::Unary : Expression
{
    Unary(Token op, std::unique_ptr<Expression> right);
    void accept(Expression::Visitor& visitor) const override;
    Token op;
    std::unique_ptr<Expression> right;
};


struct Expression::Variable : Expression
{
    Variable(Token name);
    void accept(Expression::Visitor& visitor) const override;
    Token name;
};


struct Expression::Assignment : Expression
{
    Assignment(Token name, std::unique_ptr<Expression> value);
    void accept(Expression::Visitor& visitor) const override;
    Token name;
    std::unique_ptr<Expression> value;
};


struct Statement
{
    class Visitor;
    class Expression;
    class Print;
    class VariableDeclaration;
    class Block;
    class IfElse;
    class WhileLoop;
    virtual ~Statement() = default;
    virtual void accept(Visitor& visitor) const = 0;
};


struct Statement::Expression : Statement
{
    Expression(std::unique_ptr<::Expression> expression);
    void accept(Statement::Visitor& visitor) const override;
    std::unique_ptr<::Expression> expression;
};


struct Statement::Print : Statement
{
    Print(Token keyword, std::unique_ptr<::Expression> expression);
    void accept(Statement::Visitor& visitor) const override;
    Token keyword;
    std::unique_ptr<::Expression> expression;
};


struct Statement::VariableDeclaration : Statement
{
    VariableDeclaration(Token name, std::unique_ptr<::Expression> initializer);
    void accept(Statement::Visitor& visitor) const override;
    Token name;
    std::unique_ptr<::Expression> initializer;
};


struct Statement::Block : Statement
{
    Block(std::vector<std::unique_ptr<Statement>> statements);
    void accept(Statement::Visitor& visitor) const override;
    std::vector<std::unique_ptr<Statement>> statements;
};


struct Statement::IfElse : Statement
{
    IfElse(std::unique_ptr<::Expression> condition, Token if_keyword, std::unique_ptr<Statement> then_statement, std::optional<Token> else_keyword, std::unique_ptr<Statement> else_statement);
    void accept(Statement::Visitor& visitor) const override;
    std::unique_ptr<::Expression> condition;
    Token if_keyword;
    std::unique_ptr<Statement> then_statement;
    std::optional<Token> else_keyword;
    std::unique_ptr<Statement> else_statement;
};


struct Statement::WhileLoop : Statement
{
    WhileLoop(Token keyword, std::unique_ptr<::Expression> condition, std::unique_ptr<Statement> body);
    void accept(Statement::Visitor& visitor) const override;
    Token keyword;
    std::unique_ptr<::Expression> condition;
    std::unique_ptr<Statement> body;
};


class Expression::Visitor
{
public:
    virtual void visit(const Expression::Binary& binary) = 0;
    virtual void visit(const Expression::Grouping& grouping) = 0;
    virtual void visit(const Expression::Literal& literal) = 0;
    virtual void visit(const Expression::Unary& unary) = 0;
    virtual void visit(const Expression::Variable& variable) = 0;
    virtual void visit(const Expression::Assignment& assignment) = 0;
};


class Statement::Visitor
{
public:
    virtual void visit(const Statement::Expression& expression) = 0;
    virtual void visit(const Statement::Print& print) = 0;
    virtual void visit(const Statement::VariableDeclaration& variable_declaration) = 0;
    virtual void visit(const Statement::Block& block) = 0;
    virtual void visit(const Statement::IfElse& if_else) = 0;
    virtual void visit(const Statement::WhileLoop& while_loop) = 0;
};
