/*
 * This file was generated by the generate_ast.py script.
 */

#include "ast.hpp"


void Binary::accept(Visitor& visitor) const { visitor.visit(*this); }


void Grouping::accept(Visitor& visitor) const { visitor.visit(*this); }


void Literal::accept(Visitor& visitor) const { visitor.visit(*this); }


void Unary::accept(Visitor& visitor) const { visitor.visit(*this); }
