/*
 * This file was generated by the generate_ast.py script.
 */

#include "ast.hpp"


void Expression::Binary::accept(Expression::Visitor& visitor) const { visitor.visit(*this); }


void Expression::Grouping::accept(Expression::Visitor& visitor) const { visitor.visit(*this); }


void Expression::Literal::accept(Expression::Visitor& visitor) const { visitor.visit(*this); }


void Expression::Unary::accept(Expression::Visitor& visitor) const { visitor.visit(*this); }
