/*
 * This file was generated by the generate_ast.py script.
 */

#include <variant>
#include <memory>

#include "lexer.hpp"


struct Expression
{
    class Visitor;
    class Binary;
    class Grouping;
    class Literal;
    class Unary;
    virtual void accept(Visitor& visitor) const = 0;
};


struct Expression::Binary : Expression
{
    void accept(Expression::Visitor& visitor) const override;
    const std::unique_ptr<Expression> left;
    const Token op;
    const std::unique_ptr<Expression> right;
};


struct Expression::Grouping : Expression
{
    void accept(Expression::Visitor& visitor) const override;
    const std::unique_ptr<Expression> expression;
};


struct Expression::Literal : Expression
{
    void accept(Expression::Visitor& visitor) const override;
    const std::variant<std::nullptr_t, std::string, double, bool> value;
};


struct Expression::Unary : Expression
{
    void accept(Expression::Visitor& visitor) const override;
    const Token op;
    const std::unique_ptr<Expression> right;
};


class Expression::Visitor
{
public:
    virtual void visit(const Expression::Binary& binary) = 0;
    virtual void visit(const Expression::Grouping& grouping) = 0;
    virtual void visit(const Expression::Literal& literal) = 0;
    virtual void visit(const Expression::Unary& unary) = 0;
};
